In [16]:
from sklearn.svm import SVC
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [17]:
svm = SVC(kernel='linear',C=1)

In [31]:
LA_LAkernal = pd.read_csv(f'./Result/Code_Result/LosAngeles_dis_count_rgb_withBueKernel_modified.csv')
Bue_LAkernal = pd.read_csv(f'./Result/Code_Result/BuenosAires_dis_count_rgb_withBueKernel_modified.csv')

In [32]:
LA_withB_np = LA_LAkernal.values[:,1:]
Bue_np = Bue_LAkernal.values[:,1:]

In [33]:
dataset = np.concatenate((LA_withB_np,Bue_np),axis=0)

In [34]:
dataset

array([[0.0001860984460779, 0.0026984274681306, 0.2427188982971992, ...,
        0.0006978691727924, 'LosAngeles',
        'LosAngeles_0000776_2014_03_319_34.05330975954035_-118.2492702176233_v-fUrI9TqL063X0LDtYoOw.jpg'],
       [0.0, 0.0090497737556561, 0.3240515140967629, ...,
        0.0281935259310824, 'LosAngeles',
        'LosAngeles_0000806_2009_04_392_34.05435179626063_-118.2552995922054_Tknfl8YVEsZjVpltTzRAVQ.jpg'],
       [0.0094928125847572, 0.4420938432329807, 0.0, ...,
        0.0037971250339029, 'LosAngeles',
        'LosAngeles_0000657_2014_03_140_34.05039457284261_-118.2598544272056_a5imXKIItXP_v_JGgfv4EQ.jpg'],
       ...,
       [0.0013352323304254, 0.0202065159337724, 0.1259569165034716, ...,
        0.0496706426918283, 'BuenosAires',
        'BuenosAires_0000666_2013_10_386_-34.6031675264307_-58.40853101837855_ZLjpV3OuiremuA1v-nN2XQ.jpg'],
       [0.0001572821642025, 0.0022805913809374, 0.5176942434727901, ...,
        0.002988361119849, 'BuenosAires',
        'Buen

In [40]:
X = dataset[:,:8]
y = dataset[:,8:10]

In [41]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33,random_state=42)

In [42]:
city2label = {
    'BuenosAires':'0',
    'LosAngeles':'1'
}

In [43]:
y_train_label,y_train_name = y_train[:,0],y_train[:,1]
y_test_label,y_test_name = y_test[:,0],y_test[:,1]

In [44]:
y_train_label = np.array([city2label[i] for i in y_train_label])

In [45]:
y_test_label = np.array([city2label[i] for i in y_test_label])

In [46]:
svm.fit(X_train,y_train_label)

SVC(C=1, kernel='linear')

In [47]:
predict = svm.predict(X_test)

In [48]:
np.sum(predict == y_test_label) / len(predict)

0.6339092872570194

k = 16 64.735

In [93]:
np.where((predict == y_test_label) == False)

(array([  78,  126,  657, 1256]),)

In [106]:
print(X_test[1256])

[0.4737762237762238 0.0034965034965034 0.0034965034965034 0.0 0.0
 0.0279720279720279 0.486013986013986 0.0052447552447552]


In [94]:
LA_withB_np[:10]

array([[0.9276763336913711, 0.0025062656641604, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0698174006444683, 'LosAngeles',
        'LosAngeles_0000000_2009_04_349_34.03206494429377_-118.2687816320888_tZDWhTSSOND_cUDjVnKBvw.jpg'],
       [0.7599001663893511, 0.0, 0.1156405990016638, 0.0001663893510815,
        0.0008319467554076, 0.0, 0.0901830282861896, 0.0332778702163061,
        'LosAngeles',
        'LosAngeles_0000000_2014_05_345_34.03205228756106_-118.2687736909465_mN3qmG5aUddC0Zm31qnthA.jpg'],
       [0.7189798921039725, 0.0, 0.075649828347229, 0.0,
        0.0004904364884747, 0.0, 0.192251103482099, 0.0126287395782246,
        'LosAngeles',
        'LosAngeles_0000000_2015_03_342_34.03205250798099_-118.268774871231_WNl9ZzYN5TVHHn2-heUE8w.jpg'],
       [0.5379064845102944, 0.0, 0.0365595535886088, 0.0001924187030979,
        0.0018279776794304, 0.0, 0.3709832595728304, 0.0525303059457379,
        'LosAngeles',
        'LosAngeles_0000000_2019_04_333_34.03204732470335_-118.2687749324978_q

In [50]:
Bue_np[:10]

array([[0.1164658634538152, 0.3775100401606425, 0.0305220883534136, 0.0,
        0.0, 0.2730923694779116, 0.1405622489959839, 0.0618473895582329,
        'BuenosAires',
        'BuenosAires_0000002_2013_10_527_-34.62747324853723_-58.4205645899894_qaGmmFg5L2XJS3gg1G-T_w.jpg'],
       [0.1647619732144996, 0.158317161407796, 0.0675627111334722,
        0.0326313519729749, 0.0939409185653705, 0.1522556841323462,
        0.1741297108220129, 0.1564004887515273, 'BuenosAires',
        'BuenosAires_0000002_2017_11_534_-34.62748768460501_-58.42055101764163_mnRsxXum5o9HUk-qF0v0zQ.jpg'],
       [0.1503944773175542, 0.1365877712031558, 0.0399408284023668,
        0.0547337278106508, 0.1538461538461538, 0.1099605522682445,
        0.1691321499013806, 0.1854043392504931, 'BuenosAires',
        'BuenosAires_0000003_2013_10_404_-34.62729593651334_-58.41898399723422_9V7ntN3mq3KwnfG57BMTTQ.jpg'],
       [0.1301184590989646, 0.1667754873612536, 0.0697696110437459,
        0.0430929950564313, 0.1223766439